force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Stripe Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Scheduled-Synchronisations/StripeCustomerSyncService.cls
public with sharing class StripeCustomerSyncService {
  public static StripeCustomerSyncBatchResponseWrapper syncCustomer(
    Stripe_Customer__c customer
  ) {
    Http http = new Http();
    HttpRequest req = new HttpRequest();
    req.setEndpoint(
      'callout:STRIPE_NAMED_CREDENTIAL' +
        '/v1/customers/' +
        customer.Stripe_Customer_ID__c
    );
    req.setMethod('GET');
    req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
    HttpResponse res = http.send(req);
    StripeCustomerSyncBatchResponseWrapper wrapper = (StripeCustomerSyncBatchResponseWrapper) JSON.deserialize(
      res.getBody(),
      StripeCustomerSyncBatchResponseWrapper.class
    );
    return wrapper;
  }
}