force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Stripe Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <label>Customer Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OutboundIntegration/Queueables/StripeUpdateCustomerQueueable.cls
public with sharing class StripeUpdateCustomerQueueable implements Queueable, Database.AllowsCallouts {
  private Map<Id, Stripe_Customer__c> updateStripeCustomersMap;

  public StripeUpdateCustomerQueueable(
    Map<Id, Stripe_Customer__c> updateStripeCustomersMap
  ) {
    this.updateStripeCustomersMap = updateStripeCustomersMap;
  }

  public void execute(QueueableContext qc) {
    List<Stripe_Customer__c> customerList = [
      SELECT
        Id,
        Customer_Name__c,
        Customer_Email__c,
        Customer_Phone__c,
        Stripe_Customer_ID__c
      FROM Stripe_Customer__c
      WHERE
        Id IN :updateStripeCustomersMap.keySet()
        AND Stripe_Customer_ID__c != NULL
    ];

    for (Stripe_Customer__c customer : customerList) {
      updateCustomer(customer);
    }
  }

  private void updateCustomer(Stripe_Customer__c customer) {
    Http http = new Http();
    HttpRequest req = new HttpRequest();
    req.setEndpoint(
      'callout:STRIPE_NAMED_CREDENTIAL' +
        '/v1/customers/' +
        customer.Stripe_Customer_ID__c
    );
    req.setMethod('POST');
    req.setHeader('Content-Type', 'application/x-www-form-urlencoded');

    String body = '';
    if (!String.isBlank(customer.Customer_Name__c))
      body +=
        'name=' +
        EncodingUtil.urlEncode(customer.Customer_Name__c, 'UTF-8') +
        '&';
    if (!String.isBlank(customer.Customer_Email__c))
      body +=
        'email=' +
        EncodingUtil.urlEncode(customer.Customer_Email__c, 'UTF-8') +
        '&';
    if (!String.isBlank(customer.Customer_Phone__c))
      body +=
        'phone=' +
        EncodingUtil.urlEncode(customer.Customer_Phone__c, 'UTF-8') +
        '&';

    if (body.endsWith('&')) {
      body = body.substring(0, body.length() - 1);
    }
    System.debug('Stripe request body for ' + customer.Id + ': ' + body);
    req.setBody(body);

    try {
      HttpResponse res = http.send(req);

      if (res.getStatusCode() == 200) {
        Logger.info('Stripe Customer Updated Successfully ' + customer.Id);
      } else {
        Logger.error(
          'Stripe failed to update Subscription ' +
            customer.Id +
            ' : ' +
            res.getBody()
        );
        Logger.saveLog();
      }
    } catch (Exception e) {
      Logger.error(
        'Stripe update exception for ' + customer.Id + ' : ' + e.getMessage()
      );
      Logger.saveLog();
    }
  }
}