force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Stripe Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>incomplete</fullName>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>incomplete_expired</fullName>
                <label>Incomplete Expired</label>
            </value>
            <value>
                <fullName>past_due</fullName>
                <label>Past Due</label>
            </value>
            <value>
                <fullName>trialing</fullName>
                <label>Trialing</label>
            </value>
            <value>
                <fullName>unpaid</fullName>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipLabel>Stripe Subscriptions</relationshipLabel>
    <relationshipName>Stripe_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Subscription ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Subscription_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Item_ID__c</fullName>
    <label>Stripe Subscription Item ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Status of synchronization with Stripe</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Send to Stripe</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
1
                <label>Pending</label>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Checkout Created</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Inbound-Integration/Tests/StripeSubscriptionWebhookStrategyTest.cls
@isTest
public with sharing class StripeSubscriptionWebhookStrategyTest {
  @isTest
  static void testHandleCreateSubscriptionSuccess() {
    Stripe_Customer__c newCustomer = new Stripe_Customer__c();
    newCustomer.Customer_Email__c = 'test@email.com';
    insert newCustomer;
    Stripe_Subscription__c newSubscription = new Stripe_Subscription__c();
    newSubscription.Stripe_Customer__c = newCustomer.Id;
    //newSubscription.Stripe_Subscription_ID__c
    //When the Stripe Subscription record is created is Salesforce, Stripe's subscription ID is not yet known. We will get this information from the webhook event.
    insert newSubscription;

    String subscriptionId = newSubscription.Id;

    String jsonString = StripeWebhookTestFixtures.subscriptionEvents(
      subscriptionId,
      'customer.subscription.created'
    );

    Test.startTest();

    StripeSubscriptionWebhookStrategy strategy = new StripeSubscriptionWebhookStrategy();
    Integer result = strategy.handle(jsonString);

    Test.stopTest();

    Stripe_Subscription__c createdSubscription = [
      SELECT
        Stripe_Subscription_ID__c,
        Stripe_Subscription_Item_ID__c,
        Sync_Status__c
      FROM Stripe_Subscription__c
      WHERE Id = :subscriptionId
      LIMIT 1
    ];

    Assert.areEqual(204, result, 'Expected the operation to succeed');
    Assert.areNotEqual(
      null,
      createdSubscription.Stripe_Subscription_ID__c,
      'Stripe_Subscription_ID__c should not be null'
    );
    Assert.areNotEqual(
      null,
      createdSubscription.Stripe_Subscription_Item_ID__c,
      'Stripe_Subscription_Item_ID__c should not be null.'
    );
    Assert.areEqual(
      'Synced',
      createdSubscription.Sync_Status__c,
      'Sync status does not match. Expected: Synced. Actual: ' +
      createdSubscription.Sync_Status__c
    );
  }

  /**
   * @description This tests handling of a request body that does not include the record id for the Stripe_Subscription__c record in Salesforce. This method should return a response code of 422
   */
  @isTest
  static void testHandleCreateSubscriptionIdNull() {
    Stripe_Customer__c newCustomer = StripeTestDataFactory.createStripeCustomer(
      true
    );
    Stripe_Subscription__c newSubscription = StripeTestDataFactory.createStripeSubscription(
      true,
      newCustomer.Id
    );
    String jsonString = StripeWebhookTestFixtures.subscriptionEvents(
      null,
      'customer.subscription.created'
    );

    Test.startTest();

    StripeSubscriptionWebhookStrategy strategy = new StripeSubscriptionWebhookStrategy();
    Integer result = strategy.handle(jsonString);

    Test.stopTest();

    Assert.areEqual(422, result, 'Expected response code 422');
  }

  /**
   * @description This tests handling of a request body that does not include the record id for the Stripe_Subscription__c record in Salesforce. This method should return a response code of 422
   */
  @isTest
  static void testHandleCancelSubscriptionIdNull() {
    Stripe_Customer__c newCustomer = StripeTestDataFactory.createStripeCustomer(
      true
    );
    Stripe_Subscription__c newSubscription = StripeTestDataFactory.createStripeSubscription(
      true,
      newCustomer.Id
    );
    String jsonString = StripeWebhookTestFixtures.subscriptionEvents(
      null,
      'customer.subscription.deleted'
    );

    Test.startTest();

    StripeSubscriptionWebhookStrategy strategy = new StripeSubscriptionWebhookStrategy();
    Integer result = strategy.handle(jsonString);

    Test.stopTest();

    Assert.areEqual(422, result, 'Expected response code 422');
  }

  /**
   * @description This tests handling of a request body that does not include the record id for the Stripe_Subscription__c record in Salesforce. This method should return a response code of 422
   */
  @isTest
  static void testHandleUpdateSubscriptionIdNull() {
    Stripe_Customer__c newCustomer = StripeTestDataFactory.createStripeCustomer(
      true
    );
    Stripe_Subscription__c newSubscription = StripeTestDataFactory.createStripeSubscription(
      true,
      newCustomer.Id
    );
    String jsonString = StripeWebhookTestFixtures.subscriptionEvents(
      null,
      'customer.subscription.updated'
    );

    Test.startTest();

    StripeSubscriptionWebhookStrategy strategy = new StripeSubscriptionWebhookStrategy();
    Integer result = strategy.handle(jsonString);

    Test.stopTest();

    Assert.areEqual(422, result, 'Expected response code 422');
  }

  @isTest
  static void testHandleUpdateSubscriptionSuccess() {
    Stripe_Customer__c newCustomer = new Stripe_Customer__c();
    newCustomer.Customer_Email__c = 'test@email.com';
    insert newCustomer;
    Stripe_Subscription__c newSubscription = new Stripe_Subscription__c();
    newSubscription.Stripe_Customer__c = newCustomer.Id;
    //newSubscription.Stripe_Subscription_ID__c
    //When the Stripe Subscription record is created is Salesforce, Stripe's subscription ID is not yet known. We will get this information from the webhook event.
    insert newSubscription;

    String subscriptionId = newSubscription.Id;

    String jsonString = StripeWebhookTestFixtures.subscriptionEvents(
      subscriptionId,
      'customer.subscription.updated'
    );

    Test.startTest();

    StripeSubscriptionWebhookStrategy strategy = new StripeSubscriptionWebhookStrategy();
    Integer result = strategy.handle(jsonString);

    Test.stopTest();

    Stripe_Subscription__c updatedSubscription = [
      SELECT Amount__c
      FROM Stripe_Subscription__c
      WHERE Id = :subscriptionId
      LIMIT 1
    ];

    Assert.areEqual(204, result, 'Expected the operation to succeed');
    Assert.areEqual(
      80.00,
      updatedSubscription.Amount__c,
      'Expected 80.00, actual: ' + updatedSubscription.Amount__c
    );
  }

  @isTest
  static void testHandleCancelSubscriptionSuccess() {
    Stripe_Customer__c newCustomer = new Stripe_Customer__c();
    newCustomer.Customer_Email__c = 'test@email.com';
    insert newCustomer;
    Stripe_Subscription__c newSubscription = new Stripe_Subscription__c();
    newSubscription.Stripe_Customer__c = newCustomer.Id;
    newSubscription.Stripe_Subscription_ID__c = 'sub_1RwbCy4hwnEBsWxgVxLeHnl4';
    insert newSubscription;

    String subscriptionId = String.valueOf(newSubscription.Id);
    String jsonString = StripeWebhookTestFixtures.subscriptionEvents(
      subscriptionId,
      'customer.subscription.deleted'
    );

    Test.startTest();

    StripeSubscriptionWebhookStrategy strategy = new StripeSubscriptionWebhookStrategy();
    Integer result = strategy.handle(jsonString);

    Test.stopTest();

    Stripe_Subscription__c updatedSubscription = [
      SELECT Status__c
      FROM Stripe_Subscription__c
      WHERE Id = :subscriptionId
      LIMIT 1
    ];

    Assert.areEqual(204, result, 'Expected the operation to succeed');
    Assert.areEqual(
      'canceled',
      updatedSubscription.Status__c,
      'Expected status to be canceled, actual status: ' +
      updatedSubscription.Status__c
    );
  }
}