force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Stripe Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <label>Customer Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Payment_Method__c</fullName>
    <label>Default Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Inbound-Integration/Strategies/StripeCustomerWebhookStrategy.cls
/**
 * @description Contains the logic for handling Stripe inbound customer events
 *
 * @author Jonathan Lyles
 * @date August 25, 2025
 * @group Stripe Inbound Integration
 */

public without sharing class StripeCustomerWebhookStrategy implements IStripeWebhookStrategy {
  /**
   * @description Main method for all inbound customer events
   *
   * @return Integer Http response code
   */
  public Integer handle(String requestBody) {
    Logger.info('Executing customer strategy');

    StripeWebhookCustomerWrapper wrapper = StripeWebhookCustomerWrapper.parse(
      requestBody
    );

    Integer result;

    // Exit if this event is not supported
    if (wrapper.type != 'customer.updated') {
      Logger.error('No support for this strategy');
      return 404;
    }

    result = customerUpdate(wrapper);
    return result;
  }

  /**
   * @description Contains the logic for customer update events
   *
   * @return Integer Http response code
   */
  public Integer customerUpdate(StripeWebhookCustomerWrapper wrapper) {
    String customerId = wrapper.data.object_x.id;

    Stripe_Customer__c customer = [
      SELECT
        Customer_Email__c,
        Customer_Name__c,
        Customer_Phone__c,
        Default_Payment_Method__c,
        Stripe_Customer_ID__c
      FROM Stripe_Customer__c
      WHERE Stripe_Customer_ID__c = :customerId
    ];

    customer.Customer_Email__c = wrapper.data.object_x.email;
    customer.Customer_Name__c = wrapper.data.object_x.name;
    customer.Customer_Phone__c = wrapper.data.object_x.phone;
    customer.Default_Payment_Method__c = wrapper.data.object_x.default_source;

    try {
      update customer;
    } catch (DmlException e) {
      Logger.error(e.getMessage());
      return 422;
    } catch (Exception e) {
      Logger.error(e.getMessage());
      return 500;
    }
    return 204;
  }
}

//TODO: are these logs being saved when the program runs?
//TODO: are these values being return?