force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Stripe Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <label>Customer Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/OutboundIntegration/Service/StripeCustomerService.cls
public with sharing class StripeCustomerService {
  public static void handleUpdateStripeCustomers(
    Map<Id, Stripe_Customer__c> oldStripeCustomersMap,
    Map<Id, Stripe_Customer__c> newStripeCustomersMap
  ) {
    if (newStripeCustomersMap == null || newStripeCustomersMap.isEmpty()) {
      return;
    }

    Map<Id, Stripe_Customer__c> updateStripeCustomersMap = new Map<Id, Stripe_Customer__c>();

    for (Id custId : newStripeCustomersMap.keySet()) {
      Stripe_Customer__c newRec = newStripeCustomersMap.get(custId);
      Stripe_Customer__c oldRec = oldStripeCustomersMap.get(custId);

      if (hasSyncableFieldsChanged(newRec, oldRec)) {
        updateStripeCustomersMap.put(custId, newRec);
      }
    }

    if (!updateStripeCustomersMap.isEmpty()) {
      System.enqueueJob(
        new StripeUpdateCustomerQueueable(updateStripeCustomersMap)
      );
    }
  }

  private static Boolean hasSyncableFieldsChanged(
    Stripe_Customer__c newRec,
    Stripe_Customer__c oldRec
  ) {
    return newRec.Customer_Name__c != oldRec.Customer_Name__c ||
      newRec.Customer_Email__c != oldRec.Customer_Email__c ||
      newRec.Customer_Phone__c != oldRec.Customer_Phone__c;
  }
}