force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PMT-{000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Type__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>card</fullName>
                <label>Card</label>
            </value>
            <value>
                <fullName>bank_account</fullName>
                <label>Bank Account</label>
            </value>
            <value>
                <fullName>ach_debit</fullName>
                <label>ACH Debit</label>
            </value>
            <value>
                <fullName>wire_transfer</fullName>
                <label>Wire Transfer</label>
            </value>
            <value>
                <fullName>other</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>open</fullName>
                <default>true</default>
                <label>open</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Stripe_Payment_Intent_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Intent_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Payment Intent ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Stripe_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Subscription</label>
    <referenceTo>Stripe_Subscription__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Stripe Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>incomplete</fullName>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>incomplete_expired</fullName>
                <label>Incomplete Expired</label>
            </value>
            <value>
                <fullName>past_due</fullName>
                <label>Past Due</label>
            </value>
            <value>
                <fullName>trialing</fullName>
                <label>Trialing</label>
            </value>
            <value>
                <fullName>unpaid</fullName>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipLabel>Stripe Subscriptions</relationshipLabel>
    <relationshipName>Stripe_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Stripe_Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Subscription ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Inbound-Integration/Strategies/StripePaymentWebhookStrategy.cls
/**
 * @description Logic for handling Stripe invoice webhook events
 *
 * @author Jonathan Lyles
 * @date August 25, 2025
 * @group Stripe Inbound Integration
 */

public without sharing class StripePaymentWebhookStrategy implements IStripeWebhookStrategy {
  /**
   * @description The main method for handling Stripe invoice webhook events
   *
   * @return Integer Http status code
   */

  public Integer handle(String requestBody) {
    Logger.info('Executing payment strategy');

    StripeWebhookInvoiceWrapper wrapper = StripeWebhookInvoiceWrapper.parse(
      requestBody
    );

    Integer result;
    switch on wrapper.type {
      when 'invoice.paid' {
        result = invoicePaid(wrapper);
      }
      // when 'customer.subscription.deleted' {
      //   result = invoicePaymentFailed(wrapper);
      // }
    }

    return result;
  }

  /**
   * @description Logic for invoice paid events
   *
   * @return Integer http response code
   */
  public Integer invoicePaid(StripeWebhookInvoiceWrapper wrapper) {
    Integer result;
    //TODO: add validation that wrapper has all the required data to proceed
    Stripe_Subscription__c sub = getSubscription(wrapper);

    Payment_Transaction__c payment = new Payment_Transaction__c();
    payment.Amount__c = wrapper.data.object_x.amount_paid;
    payment.Currency__c = wrapper.data.object_x.currency_x;
    payment.Transaction_Date__c = DateUtils.timestampToDatetimeConverter(
      wrapper.created
    );

    // Payment_Method_Type__c field hidden: invoice.paid request body does not specify the payment method type

    // Busines Decision: Stripe Payment Intent ID is populated with the invoice ID
    payment.Stripe_Payment_Intent_ID__c = wrapper.data.object_x.id;
    payment.Status__c = 'Succeeded';
    payment.Stripe_Customer__c = sub.Stripe_Customer__c;
    payment.Stripe_Subscription__c = sub.Id;

    try {
      insert payment;
      Logger.info(
        'Payment transaction ' + payment.Id + ' successfully inserted.'
      );
      result = 201;
    } catch (DmlException e) {
      System.debug('DML Exception');

      result = 422;
    } catch (Exception e) {
      Logger.error(e.getMessage());

      result = 500;
    }
    Logger.saveLog();
    return result;
  }

  /**
   * @description The logic for handling invoice payment failed events
   *
   * @return Integer Http response code
   */

  //TODO: still needs to be done
  // public Integer invoicePaymentFailed(StripeWebhookInvoiceWrapper wrapper) {
  //   //TODO: Do I need a separate event or use invoicePaid? Does a failed payment contain a request that has all the info needed to use that method?
  // }

  /**
   * @description Helper method retrieves Stripe Subscription record
   *
   * @return Stripe_Subscription__c
   */
  public Stripe_Subscription__c getSubscription(
    StripeWebhookInvoiceWrapper wrapper
  ) {
    String subId = getSubscriptionId(wrapper);

    Stripe_Subscription__c sub = [
      SELECT Id, Stripe_Customer__c, Stripe_Subscription_ID__c
      FROM Stripe_Subscription__c
      WHERE Id = :subId
      //Jason changed 8/29/25
      //WHERE Stripe_Subscription_ID__c = :subId
      LIMIT 1
    ];

    return sub;
  }

  //TODO: Do I still need this?
  /**
   * @description Helpler method. Gets Stripe subscription id
   *
   * @return String Stripe subscription Id
   */
  public String getSubscriptionId(StripeWebhookInvoiceWrapper wrapper) {
    // String subId = wrapper.data.object_x.lines.data[0]
    //   .parent.subscription_item_details.subscription;
    //Jason added 8/29/25
    String subId = wrapper.data.object_x.lines.data[0].metadata.get('Salesforce_Subscription_Id');
    return subId;
  }

  /**
   * @description Helper method. Gets the Salesforce Stripe_Subscription__c record
   *
   * @return Stripe_Subscription__c
   */
}